onCull = true
maxEntityEntities = 128
entitiesDistance = 64
QualityModes = "NORMAL"
RenderWeather = "NORMAL"
RenderTNTExplosions = true
FastItemRender = false
RenderDisplayItem = false
blackListedEntities = []
whiteListedEntities = []
isAlwaysShowItemCount = true
